name: Documentation
# This job builds and deploys documenation to github pages.
# It runs on every push to master.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: tendermintdev/docker-website-deployment
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.5.0
        with:
          persist-credentials: false
          fetch-depth: 0
