name: "Nightly E2E run"
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    # run every day at 03:00 UTC
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *  
    - cron: "0 0 * * *"

jobs:

  run-tests:
    uses: mmulji-ic/gaia/.github/workflows/test.yml@main

  run-simulations:
    uses: mmulji-ic/gaia/.github/workflows/sims.yml@main

  run-vulncheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19.1
      - name: run-vulncheck
        id: vulncheck
        run: make vulncheck

  run-vulncheck-test-notification:
    if: failure()
    needs: run-vulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on failure
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          BRANCH: ${{ github.ref_name }}
          RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          COMMITS_URL: "${{ github.server_url }}/${{ github.repository }}/commits/${{ github.ref_name }}"
        with:
          payload: |
            {
              "blocks": [
                  {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❗govulncheck failed on the nightly build, see the <${{ env.RUN_URL }}|run details>",
                    "emoji" : true
                  }                  
                }
              ]
            }
