name: "Nightly E2E run"
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  matrix-tests:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]       # We can add custom runners - https://github.com/actions/runner
    runs-on: ${{ matrix.os }}
    steps:
      - name: run-tests
        uses: cosmos/gaia/.github/workflows/test.yml@main
      - name: run-simulations
        uses: cosmos/gaia/.github/workflows/sims.yml@main

  run-vulncheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
      - name: run-vulncheck
        id: vulncheck
        run: make vulncheck

  warn-if-failure:
    if: failure()
    needs: [ run-tests, run-vulncheck, run-simulations]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on failure
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.NIGHTLY_E2E_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          BRANCH: ${{ github.ref_name }}
          RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          COMMITS_URL: "${{ github.server_url }}/${{ github.repository }}/commits/${{ github.ref_name }}"
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❗Nightly tests failed",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "See the <${{ env.RUN_URL }}|run details>"
                  }
                }
              ]
            }
